tests/bench_msg_pingpong: cast void* to atomic_flag*
fixes a compile error with clang if current clang stdatomics.h is used:
```
/home/kaspar/src/riot.rs/tests/bench_msg_pingpong/main.c:38:5: error: member reference base type 'void' is not a structure or union
    atomic_flag_clear(flag);
    ^~~~~~~~~~~~~~~~~~~~~~~
/home/kaspar/src/riot.rs/sys/libc/include/clang/stdatomic.h:181:63: note: expanded from macro 'atomic_flag_clear'
                                                      ~~~~~~~~^ ~~~~~~
1 error generated.
```